# Generated by Django 4.0.4 on 2022-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='display_course_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='display_subject_name',
        ),
        migrations.AddField(
            model_name='course',
            name='url_course_name',
            field=models.CharField(default='hello', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='url_subject_name',
            field=models.CharField(default='h3llo', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
