# Generated by Django 4.0.4 on 2022-05-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_rename_course_name_course_display_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Imagem Ilustrativa',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
