# Generated by Django 4.0.4 on 2022-05-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_course_imagem ilustrativa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Imagem Ilustrativa',
            new_name='background_img',
        ),
        migrations.AddField(
            model_name='course',
            name='img_description',
            field=models.CharField(default=models.CharField(max_length=50, unique=True), max_length=50),
        ),
    ]
