# Generated by Django 4.0.4 on 2022-05-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0004_rename_imagem ilustrativa_course_background_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='background_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
