# Generated by Django 4.0.4 on 2022-05-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0005_alter_course_background_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='resumos/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.subject')),
            ],
        ),
    ]
